name: ${pluginName}
version: ${version}
main: com.willfp.ecocollections.EcoCollectionsPlugin
api-version: "1.21"
authors: [CallumJohnson]
depend:
  - eco
softdepend:
  - libreforge
  - PlaceholderAPI
commands:
  collections:
    aliases: [coll, collection]
  ecocollections:
    aliases: [ecoc]
permissions:
  ecocollections.command.collections:
    default: true
  ecocollections.command.admin:
    default: op
